openapi: 3.0.0
info:
  title: Placement API
  version: 1.0.0
paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /hello/{name}:
    get:
      summary: Say hello
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Greeting
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
