openapi: 3.0.0
info:
  title: Virtual Machine Placement API
  version: v1alpha1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: /

paths:
  /health:
    get:
      summary: Health check
      operationId: health
      responses:
        '200':
          description: OK

  /applications:
    post:
      summary: Create an application
      operationId: createApplication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Application'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Application'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    get:
      summary: Get all applications
      operationId: getApplications
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationList'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Application:
      type: object
      required:
        - name
        - service
      properties:
        name:
          type: string
          description: Name of the application
          example: "app-server-01"
        service:
          type: string
          description: Service of the application
          enum:
            - "webserver"
        zones:
          type: array
          items:
            type: string
          description: Zones of the application
          example: ["us-east-1", "us-east-2"]
        tier:
          type: string
          description: Policy Tier of the application

    ApplicationList:
      type: array
      items:
        $ref: '#/components/schemas/Application'

    Error:
      required:
        - error
      type: object
      properties:
        error:
          type: string
          description: Error message
          example: "Invalid request parameters - Validation Failed"
        code:
          type: integer
          description: Error code
          example: 400
