openapi: 3.0.0
info:
  title: Virtual Machine Placement API
  version: v1alpha1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: /

paths:
  /health:
    get:
      summary: Health check
      operationId: health
      responses:
        '200':
          description: OK
